{% set name = "opentelemetry-instrumentation-pymongo" %}
{% set version = "0.36b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymongo-{{ version }}.tar.gz
  sha256: 362a7d47650a452a1e100fb907517df18e7a0f29697a7943c12b4c7be51934b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==0.36b0
    - opentelemetry-semantic-conventions ==0.36b0
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymongo
  summary: OpenTelemetry pymongo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
