{% set name = "typepy" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96788530614083164993d1443959f6c58e6bb8e2da839812ddf462c203e4b84c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=38.3.0
  run:
    - mbstrdecoder >=1.0.0,<2
    - python >=3.5
    - setuptools >=38.3.0

test:
  imports:
    - typepy
    - typepy.checker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/typepy
  summary: typepy is a Python library for variable type checker/validator/converter at a run time.
  dev_url: https://github.com/thombashi/typepy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
