{% set name = "restrictedpython" %}
{% set version = "6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RestrictedPython-{{ version }}.tar.gz
  sha256: 405cf0bd9eec2f19b1326b5f48228efe56d6590b4e91826b8cc3b2cd400a96ad

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python <3.12
  run:
    - python <3.12

test:
  imports:
    - RestrictedPython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/RestrictedPython
  summary: RestrictedPython is a defined subset of the Python language which allows to provide a program input into a trusted environment.
  dev_url: https://github.com/zopefoundation/RestrictedPython
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
    - hadim
