{% set name = "mosh" %}
{% set version = "1.3.2" %}
{% set sha256 = "da600573dfa827d88ce114e0fed30210689381bbdcff543c931e4d6a2e851216" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mosh.org/{{ name }}-{{ version }}.tar.gz
  sha256: da600573dfa827d88ce114e0fed30210689381bbdcff543c931e4d6a2e851216
  patches:
    - toplevel-bind.patch

build:
  number: 1005
  skip: True  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libprotobuf
    - ncurses
    - zlib
    - openssl
    - perl
  run:
    - perl

test:
  commands:
    - mosh-server -h

about:
  home: https://mosh.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: 'Mobile shell that supports roaming and intelligent local echo'

  description: |
      Mosh is a remote terminal application that supports:
          - intermittent network connectivity,
          - roaming to different IP address without dropping the connection, and
          - intelligent local echo and line editing to reduce the effects
            of "network lag" on high-latency connections.

extra:
  recipe-maintainers:
    - gokceneraslan
    - xhochy
