{% set name = "qiskit-terra" %}
{% set version = "0.23.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-terra-{{ version }}.tar.gz
  sha256: 71dfb4510b2f1fdb7589b412e8304d928534fa2eece66a65b3f841baf5412afb

build:
  number: 0
  skip: true  # [win]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - importlib-metadata <5.0
    - rustworkx >=0.12.0
    - python
    - numpy >=1.17
    - ply >=3.10
    - psutil >=5
    - scipy >=1.5
    - sympy >=1.3
    - dill >=0.3
    - python-dateutil >=2.8.0
    - stevedore >=3.0.0
    - python-symengine >=0.9
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - ipywidgets >=7.3.0
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - seaborn >=0.9.0
    - pygments >=2.4
    - z3-solver >=4.7
    - qiskit-toqm >=0.1.0
    - qiskit-qasm3-import >=0.1.0

test:
  imports:
    - qiskit
    - qiskit.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-terra
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
