{% set name = "conda-package-handling" %}
{% set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-handling/archive/{{ version }}.tar.gz
  sha256: dae0c697cf8757d997d0d7f4fbe48a5516cb17f16b3715dadb6008ade8ef850e

build:
  number: 0 # trigger
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - cph = conda_package_handling.cli:main

requirements:
  # Use this build section with python to avoid an Unexpected conda error on CI
  build:
    - python
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - zstandard >=0.15
    - conda-package-streaming >=0.9.0

test:
  source_files:
    - tests
  requires:
    - mock
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests  # optional, here to please pip check
  imports:
    - conda_package_handling
    - conda_package_handling.api
  commands:
    - pip check
    - pytest -v --cov=conda_package_handling --color=yes tests/

about:
  home: https://github.com/conda/conda-package-handling
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create and extract conda packages of various formats.
  description: |
    `conda` and `conda-build` use `conda_package_handling.api` to create and extract
    conda packages. This package also provides the `cph` command line tool to
    extract, create, and convert between formats.

extra:
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
