{% set name = "google-cloud-dataproc" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-dataproc-{{ version }}.tar.gz
  sha256: 8ae8577c5a7a71f0cd0ed937252f94f186d000e208d24858d9b9af3fbe5000fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - libcst >=0.2.5
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.dataproc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-dataproc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Dataproc API client library
  description: "Google Cloud Dataproc API client library manages Hadoop-based clusters and jobs on Google Cloud Platform. With Dataproc, enterprises get a fully managed, purpose-built cluster that can autoscale to support any data or analytics processing job.\nSee the [quick start guide](https://googleapis.dev/python/dataproc/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dataproc/latest/index.html
  dev_url: https://github.com/googleapis/python-dataproc

extra:
  recipe-maintainers:
    - parthea
    - xylar
