{% set name = "requests-toolbelt" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7681a0a3d047012b5bdc0ee37d7f8f07ebe76ab08caeccfc3921ce23c88d5bc6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.0.1,<3.0.0

test:
  imports:
    - requests_toolbelt
    - requests_toolbelt.adapters
    - requests_toolbelt.auth
    - requests_toolbelt.downloadutils
    - requests_toolbelt.multipart
    - requests_toolbelt.threaded
    - requests_toolbelt.utils
  requires: 
    - pip
    - pytest
  commands: 
    - pip check

about:
  home: https://toolbelt.readthedocs.io/
  dev_url: https://github.com/requests/toolbelt
  doc_url: https://toolbelt.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A toolbelt of useful classes and functions to be used with python-requests
  description: |
    A toolbelt of useful classes and functions to be used with python-requests

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - sigmavirus24
