{% set name = "three-merge" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60f6afe144595560d63ae32625351bcef3b94733b54eb97800a9feb0f3d9d970

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - diff-match-patch

test:
  imports:
    - three_merge
    - three_merge.merge

about:
  home: https://github.com/spyder-ide/three-merge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple Python library to perform a 3-way merge between strings '
  description: |
    Simple Python library to perform a 3-way merge between strings,
    based on diff-match-patch. This library performs merges at a character
    level, as opposed to most VCS systems, which opt for a line-based approach.
  dev_url: https://github.com/spyder-ide/three-merge

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
