{% set name = "python-binance" %}
{% set version = "1.0.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-binance-{{ version }}.tar.gz
  sha256: 3796bfa0124d376cf9ad42f03168d7630de56f936613eb39d05a4b82e1b1f1eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - dateparser
    - python >=3.6
    - requests
    - six
    - ujson
    - websockets ==9.1

test:
  imports:
    - binance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sammchardy/python-binance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Binance Exchange API python implementation for automated trading
  description: |
    This is an unofficial Python wrapper for the Binance exchange REST API 
    v3. 
  doc_url: https://python-binance.readthedocs.io/
  dev_url: https://github.com/sammchardy/python-binance

extra:
  recipe-maintainers:
    - jan-janssen
