{% set name = "jmp" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/jmp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 830a802144e66d27a3acb54d203efcf47067f7c5f4b6312d29d3b65a89a4cba1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses >=0.7
    - numpy >=1.19.5
    - python >=3.6
    - jax

test:
  imports:
    - jmp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/jmp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: JMP is a Mixed Precision library for JAX.
  description: |
    Mixed precision training [0] is a technique that mixes the use of full
    and half precision floating point numbers during training to reduce
    the memory bandwidth requirements and improve the computational
    efficiency of a given model.
  doc_url: https://github.com/deepmind/jmp
  dev_url: https://github.com/deepmind/jmp

extra:
  recipe-maintainers:
    - jan-janssen
