{% set name = "ExifRead" %}
{% set version = "3.0.0" %}
{% set hash = "0ac5a364169dbdf2bd62f94f5c073970ab6694a3166177f5e448b10c943e2ca4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3

test:
  imports:
    - exifread
  commands:
    - EXIF.py --help

about:
  home: https://github.com/ianare/exif-py
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Read Exif metadata from tiff and jpeg files.
  description: |
    Easy to use Python module to extract Exif metadata from tiff and jpeg files.

extra:
  recipe-maintainers:
    - anjos
    - goanpeca
    - rlaverde
