{% set version = "3.0" %}

package:
    name: capturer
    version: {{ version }}

source:
    fn: capturer-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/capturer/capturer-{{ version }}.tar.gz
    sha256: 4849032f6a670c02be434c484a0abf43c870a1efafafbfffd2e6f1c1f7ef5001

build:
    number: 0
    skip: True  # [win]
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    host:
        - python
        - setuptools
    run:
        - python
        - humanfriendly >=2.1

test:
    imports:
        - capturer

about:
    home: https://capturer.readthedocs.org
    license: MIT
    license_file: LICENSE.txt
    summary: 'Easily capture stdout/stderr of the current process and subprocesses.'
    description: |
        The capturer package makes it easy to capture the stdout and stderr streams
        of the current process and subprocesses. Output can be relayed to the
        terminal in real time but is also available to the Python program for
        additional processing.
    dev_url: https://github.com/xolox/python-capturer
    doc_url: https://capturer.readthedocs.org

extra:
    recipe-maintainers:
        - ocefpaf
