{% set name = "bcrypt" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b93c1726e50a93a033c36e5ca7fdcd29a5c7395af50a6892f5d9e7c6cfbfb29

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi >=1.1
    - setuptools >=40.8.0
    - wheel
  run:
    - python
    - pip
    - cffi >=1.1
    - six >=1.4.1

test:
  source_files:
    - tests
  imports:
    - bcrypt
    - bcrypt._bcrypt
  requires:
    - pytest >=3.2.1,!=3.3.0
  commands:
    - pytest tests
    - pip check

about:
  home: https://github.com/pyca/bcrypt/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Modern password hashing for your software and your servers
  description: |
    Modern password hashing for your software and your servers
  doc_url: https://github.com/pyca/bcrypt/
  dev_url: https://github.com/pyca/bcrypt/

extra:
  recipe-maintainers:
    - djsutherland
    - jan-janssen
