{% set name = "wagtail" %}
{% set version = "4.2" %}
{% set sha256 = "5547551b66077c7d50dd01b1f06be0d83b89a25c65aba4446669fc7c6f31831c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wagtail=wagtail.bin.wagtail:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - anyascii >=0.1.5
    - beautifulsoup4 >=4.8,<4.12
    - django >=3.2,<4.2
    - django-filter >=2.2,<23
    - django-modelcluster >=6.0,<7.0
    - django-permissionedforms >=0.1,<1.0
    - django-taggit >=2.0,<4.0
    - django-treebeard >=4.5.1,<5.0
    - djangorestframework >=3.11.1,<4.0
    - draftjs_exporter >=2.1.5,<3.0
    - html5lib >=0.999,<2
    - l18n >=2018.5
    - pillow >=4.0.0,<10.0.0
    - python >=3.7
    - requests >=2.11.1,<3.0
    - tablib >=0.14.0
    - telepath >=0.1.1,<1
    - willow >=1.4,<1.5
    - xlsxwriter >=1.2.8,<4.0

test:
  imports:
    - wagtail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/wagtail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Django content management system focused on flexibility and user experience '
  description: |
    Wagtail is an open source content management system built on Django, with a strong community and commercial support.
    It's focused on user experience, and offers precise control for designers and developers.
  doc_url: https://docs.wagtail.org/en/stable/
  dev_url: https://github.com/wagtail/wagtail

extra:
  recipe-maintainers:
    - darynwhite
    - cshaley
    - sannykr
