{% set name = "pyhacrf-datamade" %}
{% set version = "0.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyhacrf-datamade-{{ version }}.tar.gz
  sha256: cddbd89aad5849fb8fba6f93bfea177fd02dba1b81718fd215f57b48d3d6f5ed

build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - pylbfgs
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyhacrf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dedupeio/pyhacrf
  summary: Hidden alignment conditional random field, a discriminative string edit distance
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
