{% set name = "notifiers" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/notifiers-{{ version }}.tar.gz
  sha256: 9fd8d95ab1ebcd3852423755aa90cbb0f72a805ca77af0d8c9ad7af445f58399

build:
  entry_points:
    - notifiers = notifiers_cli.core:entry_point
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - click >=8.0.3,<9.0.0
    - jsonschema >=4.4.0,<5.0.0
    - python >=3.6,<4.0
    - requests >=2.27.1,<3.0.0

test:
  imports:
    - notifiers
    - notifiers_cli
  commands:
    - pip check
    - notifiers --help
  requires:
    - pip

about:
  home: https://github.com/notifiers/notifiers
  summary: The easy way to send notifications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
