{% set name = "gTTS" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pndurette/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3764195ccb210b313ba6662083aa85e5cb39a918078048322227c46d3440a0a

build:
  number: 0
  noarch: python
  entry_points:
    - gtts-cli = gtts.cli:tts_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click ~=8.1.3
    - python >=3.7
    - requests ~=2.28.0
    - six ~=1.16.0

test:
  source_files:
    - gtts/tests
  imports:
    - gtts
    - gtts.tests
  commands:
    - pip check
    - gtts-cli --help
    - pytest -vvv --capture=tee-sys -k "not file_ascii and not file_utf8" gtts/tests
  requires:
    - mock
    - pip
    - pytest
    - testfixtures

about:
  home: https://github.com/pndurette/gTTS
  doc_url: http://gtts.readthedocs.org/
  summary: Python library and CLI tool to interface with Google Translate text-to-speech API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
