{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-diffobj
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/diffobj_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/diffobj/diffobj_{{ version }}.tar.gz
  sha256: d860a79b1d4c9e369282d7391b539fe89228954854a65ba47181407c53e3cf60

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crayon >=1.3.2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-crayon >=1.3.2

test:
  commands:
    - $R -e "library('diffobj')"           # [not win]
    - "\"%R%\" -e \"library('diffobj')\""  # [win]

about:
  home: https://github.com/brodieG/diffobj
  license: GPL-2.0-or-later
  summary: Generate a colorized diff of two R objects for an intuitive visualization of their differences.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: diffobj
# Type: Package
# Title: Diffs for R Objects
# Description: Generate a colorized diff of two R objects for an intuitive visualization of their differences.
# Version: 0.3.2
# Authors@R: c( person( "Brodie", "Gaslam", email="brodie.gaslam@yahoo.com", role=c("aut", "cre")), person( "Michael B.", "Allen", email="ioplex@gmail.com", role=c("ctb", "cph"), comment="Original C implementation of Myers Diff Algorithm"))
# Depends: R (>= 3.1.0)
# License: GPL (>= 2)
# LazyData: true
# URL: https://github.com/brodieG/diffobj
# BugReports: https://github.com/brodieG/diffobj/issues
# RoxygenNote: 7.1.0
# VignetteBuilder: knitr
# Encoding: UTF-8
# Suggests: knitr, rmarkdown, testthat
# Collate: 'capt.R' 'options.R' 'pager.R' 'check.R' 'finalizer.R' 'misc.R' 'html.R' 'styles.R' 's4.R' 'core.R' 'diff.R' 'get.R' 'guides.R' 'hunks.R' 'layout.R' 'myerssimple.R' 'rdiff.R' 'rds.R' 'set.R' 'subset.R' 'summmary.R' 'system.R' 'text.R' 'tochar.R' 'trim.R' 'word.R'
# Imports: crayon (>= 1.3.2), tools, methods, utils, stats
# NeedsCompilation: yes
# Packaged: 2020-10-05 13:55:24 UTC; bg
# Author: Brodie Gaslam [aut, cre], Michael B. Allen [ctb, cph] (Original C implementation of Myers Diff Algorithm)
# Maintainer: Brodie Gaslam <brodie.gaslam@yahoo.com>
# Repository: CRAN
# Date/Publication: 2020-10-05 17:40:06 UTC
