{% set version = "0.20.1" %}

package:
  name: azure-servicebus
  version: {{ version }}

source:
  fn: azure-servicebus-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-servicebus/azure-servicebus-{{ version }}.zip
  md5: 884d00de8e44f3e3558b22dac1e1a165
  

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - pip
    - python
    - setuptools
    - azure-common
    - requests
  run:
    - python
    - azure-common
    - requests

test:
  imports:
    - azure
    - azure.servicebus
    - azure.servicebus._http
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Service Bus Client Library for Python'

extra:
  recipe-maintainers:
    - xylar
    - Maxyme
