{% set version = '1.3-28.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-boot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/boot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/boot/boot_{{ version }}.tar.gz
  sha256: d4cde76fcc8ccc7ffa329de69147b66a6a93a10188e89342fd18207b1d02ff53

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, survival
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('boot')"           # [not win]
    - "\"%R%\" -e \"library('boot')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=boot
  license: Unlimited
  summary: Functions and datasets for bootstrapping from the book "Bootstrap Methods and Their
    Application" by A. C. Davison and D. V. Hinkley (1997, CUP), originally written
    by Angelo Canty for S.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: boot
# Priority: recommended
# Version: 1.3-28.1
# Date: 2022-11-21
# Authors@R: c(person("Angelo", "Canty", role = "aut", email = "cantya@mcmaster.ca"), person("Brian", "Ripley", role = c("aut", "trl", "cre"), email = "ripley@stats.ox.ac.uk", comment = "author of parallel support"))
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Note: Maintainers are not available to give advice on using a package they did not author.
# Description: Functions and datasets for bootstrapping from the book "Bootstrap Methods and Their Application" by A. C. Davison and D. V. Hinkley (1997, CUP), originally written by Angelo Canty for S.
# Title: Bootstrap Functions (Originally by Angelo Canty for S)
# Depends: R (>= 3.0.0), graphics, stats
# Suggests: MASS, survival
# LazyData: yes
# ByteCompile: yes
# License: Unlimited
# NeedsCompilation: no
# Packaged: 2022-11-21 22:19:52 UTC; ripley
# Author: Angelo Canty [aut], Brian Ripley [aut, trl, cre] (author of parallel support)
# Repository: CRAN
# Date/Publication: 2022-11-22 07:05:25 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
