{% set version = "0.40.0" %}

package:
  name: pixman
  version: {{ version }}

source:
  url: http://cairographics.org/releases/pixman-{{ version }}.tar.gz
  sha256: 6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc
  patches:
    - no_test.patch  # [win]

build:
  number: 1
  run_exports:
    # excellent: add new symbols sometimes, none removed.
    #    https://abi-laboratory.pro/tracker/timeline/pixman/
    - {{ pin_subpackage('pixman') }}

requirements:
  build:
    - posix  # [win]
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - make  # [unix]
    - libtool  # [unix]
    - m2-patch    # [win]
 test:
  commands:
    - test -f ${PREFIX}/lib/libpixman-1.a  # [not win]

about:
  home: http://www.pixman.org/
  license: MIT
  license_file: COPYING
  summary: 'A low-level software library for pixel manipulation.'
  description: |
    Pixman is a low-level software library for pixel manipulation, providing
    features such as image compositing and trapezoid rasterization.
  dev_url: https://cgit.freedesktop.org/pixman/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - katietz
