{% set name = "jsonmerge" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonmerge-{{ version }}.tar.gz
  sha256: a2d1f80021c5c1d70a49e31f862b5f068f9db066080d8561e80654de74a3584d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jsonschema
    - python >=3.7

test:
  imports:
    - jsonmerge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jsonmerge/
  summary: Merge a series of JSON documents.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dokempf
