{% set version = "1.4.0" %}

package:
  name: atomicwrites
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/atomicwrites/atomicwrites-{{ version }}.tar.gz
  sha256: ae70396ad1a434f9c7046fd2dd196fc04b12f9e91ffb859164193be8b6168a7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - atomicwrites

about:
  home: https://github.com/untitaker/python-atomicwrites
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Atomic file writes
  dev_url: https://github.com/untitaker/python-atomicwrites

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
    - ocefpaf
