{% set name = "email-validator" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://github.com/JoshData/python-email-validator/archive/v{{ version }}.tar.gz
  sha256: 1ac47d82c6f6b924f4cde3cf1dbd24249d2272ba338ad2aedc616838fd8d88bd

build:
  number: 0
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

outputs:
  - name: {{ name|lower }}
    build:
      entry_points:
        - email_validator = email_validator:main
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - idna >=2.0.0
        - dnspython >=1.15.0
    test:
      source_files:
        - tests
      requires:
        - coverage
        - docutils
        - flake8
        - pytest
        - pytest-cov
      imports:
        - email_validator
      commands:
        - email_validator --help
        - pytest --cov=email_validator

  # Provide package with alternative name for backward compatibility
  - name: email_validator
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('email-validator', max_pin="x.x.x") }}
    test:
      imports:
        - email_validator
      commands:
        - email_validator --help

about:
  home: https://github.com/JoshData/python-email-validator
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: A robust email syntax and deliverability validation library for 3.x.
  doc_url: https://github.com/JoshData/python-email-validator
  dev_url: https://github.com/JoshData/python-email-validator

extra:
  feedstock-name: email-validator
  recipe-maintainers:
    - xylar
    - pmlandwehr
