{% set name = "pytest-freezegun" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 19c82d5633751bf3ec92caa481fb5cffaac1787bd485f0df6436fd6242176949
  patches:
    - 0001-deprecation-warning.patch

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - freezegun >0.3
    - packaging >=14.1
    - pytest >=3.0.0
    - python >=3.6

test:
  imports:
    - pytest_freezegun

about:
  home: https://github.com/ktosiek/pytest-freezegun
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrap tests with fixtures in freeze_time
  dev_url: https://github.com/ktosiek/pytest-freezegun
  description: Wrap tests with fixtures in freeze_time

extra:
  recipe-maintainers:
    - duncanmmacleod
    - xhochy
