{% set name = "eli5" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec8459eaaf09d66743c53a7bdb115c6cda7e533d7a5d02a5a8bb717ee843eb37

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >17.1.0
    - jinja2 >=3.0.0
    - numpy >=1.9.0
    - scipy
    - singledispatch >=3.4.0.3
    - six
    - scikit-learn >=0.20
    - python-graphviz
    - tabulate >=0.7.7

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - eli5

about:
  home: https://eli5.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Debug machine learning classifiers and explain their predictions
  description: |
    ELI5 is a Python package which helps to debug machine learning classifiers
    and explain their predictions.
  doc_url: https://eli5.readthedocs.io/en/latest/
  dev_url: https://github.com/TeamHG-Memex/eli5/

extra:
  recipe-maintainers:
    - rmax
    - xhochy
