{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prettyunits
  version: {{ version|replace("-", "_") }}

source:
  fn: prettyunits_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/prettyunits_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prettyunits/prettyunits_{{ version }}.tar.gz
  sha256: 9a199aa80c6d5e50fa977bc724d6e39dae1fc597a96413053609156ee7fb75c5

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertthat
    - r-magrittr
  run:
    - r-base
    - r-assertthat
    - r-magrittr

test:
  commands:
    - $R -e "library('prettyunits')"           # [not win]
    - "\"%R%\" -e \"library('prettyunits')\""  # [win]

about:
  home: https://github.com/gaborcsardi/prettyunits
  license: MIT
  license_file: LICENSE
  summary: 'Pretty, human readable formatting of quantities. Time intervals: 1337000 -> 15d 11h
    23m 20s. Vague time intervals: 2674000 -> about a month ago. Bytes: 1337 -> 1.34
    kB.'
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
