{% set version = '0.3.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-feather
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/feather_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/feather/feather_{{ version }}.tar.gz
  sha256: 50ff06d5e24d38b5d5d62f84582861bd353b82363e37623f95529b520504adbf

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-hms
    - r-tibble >=2.0.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-hms
    - r-tibble >=2.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('feather')"           # [not win]
    - "\"%R%\" -e \"library('feather')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/wesm/feather
  license: Apache License 2.0
  summary: Read and write feather files, a lightweight binary columnar data store designed for
    maximum speed.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: feather
# Title: R Bindings to the Feather 'API'
# Version: 0.3.5
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph"), person("Feather developers", role = "ctb", comment = "Bundled feather library"), person("Google", role = "ctb", comment = "Bundled flatbuffers code"), person("LevelDB Authors", role = "ctb") )
# Description: Read and write feather files, a lightweight binary columnar data store designed for maximum speed.
# Encoding: UTF-8
# License: Apache License 2.0
# LazyData: true
# URL: https://github.com/wesm/feather
# BugReports: https://github.com/wesm/feather/issues
# LinkingTo: Rcpp
# Imports: Rcpp, tibble (>= 2.0.0), hms
# Suggests: testthat
# SystemRequirements: little-endian platform
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-09-13 21:40:20 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph], Feather developers [ctb] (Bundled feather library), Google [ctb] (Bundled flatbuffers code), LevelDB Authors [ctb]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-15 00:10:22 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
