{% set version = "1.3.2" %}

package:
  name: libwebp
  version: {{ version }}

source:
  url: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-{{ version }}.tar.gz
  sha256: 2a499607df669e40258e53d0ade8035ba4ec0175244869d1025d460562aa09b4

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libwebp
    - {{ pin_compatible('libwebp-base') }}

requirements:
  build:
    - {{ compiler('c') }}
    - gnuconfig            # [unix]
    - make                 # [unix]
  host:
    - giflib
    - jpeg
    - libpng
    - libtiff
    - libwebp-base {{ version }}.*
  run:
    - libwebp-base {{ version }}.*

test:
  source_files:
    - examples/test.webp
  commands:
  # This package is binaries only; libraries in libwebp-base. Various binaries
  # link against libtiff, libpng, libgif, so they must be separated to prevent
  # circular imports https://github.com/conda-forge/staged-recipes/pull/11101
    - test -f $PREFIX/bin/cwebp     # [not win]
    - test -f $PREFIX/bin/dwebp     # [not win]
    - test -f $PREFIX/bin/gif2webp  # [not win]
    - test -f $PREFIX/bin/img2webp  # [not win]
    - test -f $PREFIX/bin/webpinfo  # [not win]
    - test -f $PREFIX/bin/webpmux   # [not win]
  # static libs removed in 1.2.3. They are not allowed on conda-forge.
  # See also CFEP-18
    - test ! -f $PREFIX/lib/libwebdecoder.a  # [not win]
    - test ! -f $PREFIX/lib/libwebp.a        # [not win]
    - test ! -f $PREFIX/lib/libwebpdemux.a   # [not win]
    - test ! -f $PREFIX/lib/libwebpmux.a     # [not win]
    - dwebp examples/test.webp  # [not win]
    - if not exist %LIBRARY_BIN%\\cwebp.exe exit 1     # [win]
    - if not exist %LIBRARY_BIN%\\dwebp.exe exit 1     # [win]
    # - if not exist %LIBRARY_BIN%\\gif2webp.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\img2webp.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\webpinfo.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\webpmux.exe exit 1   # [win]
    - dwebp examples\\test.webp  # [win]

about:
  home: https://developers.google.com/speed/webp/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: WebP image library
  description: |
    WebP is a method of lossy and lossless compression that can be used on a large variety of photographic, 
    translucent and graphical images found on the web. 
    The degree of lossy compression is adjustable so a user can choose the trade-off between file size and image quality. 
    libwebp-base provides the headers and shared libraries. 
    For cwebp and dwep, binaries install libwebp.
  doc_url: https://developers.google.com/speed/webp/docs/using
  dev_url: https://chromium.googlesource.com/webm/libwebp

extra:
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
