{% set name = "crcmod" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crcmod-{{ version }}.tar.gz
  sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e

build:
  number: 1009
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - crcmod
    - crcmod._crcfunext

about:
  home: http://crcmod.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CRC Generator
  description: |
     Python module for generating objects that compute the Cyclic Redundancy
     Check (CRC)

extra:
  recipe-maintainers:
    - bgruening
    - chapmanb
    - xylar
    - nehaljwani
