{% set name = "bazel-toolchain" %}
{% set version = "0.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: true  # [win or s390x]

requirements:
  run_constrained:
    # This can be used without bazel from conda-forge,
    # e.g. when bootstrapping bazel itself.
    - bazel >=4

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel

about:
  home: https://github.com/conda-forge/bazel-toolchain-feedstock
  summary: Helper script to generate a crosscompile toolchain for Bazel with the currently activated compiler settings.
  description: |
    This package generates a crosstool toolchain for Bazel that uses the currently
    activated compilers / linker as defined by the environment variables. It does
    take various conda(-forge) specifics into account for this. In addition to generating
    a toolchain, it also sets various environment variables that need to be set for
    the toolchain to work. Especially you will need to pass in the correct ${TARGET_CPU}
    to ensure that cross-compiling also works.

    In build.sh

      source gen-bazel-toolchain
      bazel build --crosstool_top=//bazel_toolchain:toolchain --cpu ${TARGET_CPU} …

  license: BSD-3-Clause AND Apache-2.0
  license_file: LICENSE.txt
  license_family: OTHER
  doc_url: https://github.com/conda-forge/bazel-toolchain-feedstock
  dev_url: https://github.com/conda-forge/bazel-toolchain-feedstock

extra:
  recipe-maintainers:
    - xhochy
    - wolfv
