{% set name = "gcs-oauth2-boto-plugin" %}
{% set version = "3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcs-oauth2-boto-plugin-{{ version }}.tar.gz
  sha256: f4120b08b7f8d32904674c98f07d4caf4083a58343c0c0fa0016e0f0254dfe31

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto >=2.29.1
    - google-reauth >=0.1.0
    - httplib2 >=0.18
    - oauth2client >=2.2.0
    - pyopenssl >=0.13
    - python >=3.6
    - retry_decorator >=1.0.0
    - rsa ==4.7.2
    - six >=1.12.0

test:
  imports:
    - gcs_oauth2_boto_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gcs-oauth2-boto-plugin/
  summary: Auth plugin allowing use the use of OAuth 2.0 credentials for Google Cloud Storage in the Boto library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
