{% set name = "jbig" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://www.cl.cam.ac.uk/~mgk25/git/jbigkit
  git_tag: v{{ version }}

build:
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libjbig.a

about:
  home: https://www.cl.cam.ac.uk/~mgk25/jbigkit
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Implementation of the JBIG1 data compression standard'

  description: |
    JBIG-KIT provides a portable library of compression and decompression
    functions with a documented interface that you can include very easily
    into your image or document processing software.
  doc_url: https://www.cl.cam.ac.uk/~mgk25/jbigkit/
  dev_url: https://www.cl.cam.ac.uk/~mgk25/git/jbigkit/

extra:
  recipe-maintainers:
    - nehaljwani
    - mingwandroid
