{% set name = "Imath" %}
{% set version = "3.1.6" %}
{% set sha256 = "ea5592230f5ab917bea3ceab266cf38eb4aa4a523078d46eac0f5a89c52304db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/Imath/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - macos-portability.patch  # [osx]

build:
  number: 1
  run_exports:
    # Not yet on ABI Laboratory, but extrapolating from IlmBase:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/Imath/half.h                          # [unix]
    - test -f ${PREFIX}/include/Imath/ImathMath.h                     # [unix]
    - test -f ${PREFIX}/lib/libImath${SHLIB_EXT}                      # [unix]
    - if not exist %LIBRARY_PREFIX%\include\Imath\half.h exit 1       # [win]
    - if not exist %LIBRARY_PREFIX%\include\Imath\ImathMath.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\Imath.lib exit 1              # [win]
    - if not exist %PREFIX%\\Library\lib\pkgconfig\Imath.pc exit 1    # [win]

about:
  home: http://www.openexr.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: IMath libraries required for OpenEXR.
  doc_url: http://www.openexr.com/documentation.html

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - pkgw
