{% set name = "backports.zoneinfo" %}
{% set version = "0.2.1" %}
{% set hash = "fadbfe37f74051d024037f223b8e001611eac868b5c5b06144ef4d8b799862f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:
    - tzdata-location.patch

build:
  number: 0
  skip: true  # [py>38]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - m2-patch # [win]
    - patch # [not win]
    - setuptools >=40.0.0
    - wheel
  host:
    - backports
    - python
    - pip
  run:
    - backports
    - python
    - tzdata
    - importlib_resources  # [py<37]

test:
  imports:
    - backports.zoneinfo
  commands:
    - python -c "from backports.zoneinfo import ZoneInfo; from datetime import datetime; dt = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"

about:
  home: https://github.com/pganssle/zoneinfo
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  summary: 'Backport of the standard library zoneinfo module'

  description: |
    Backport of the standard library zoneinfo module
  doc_url: https://zoneinfo.readthedocs.io/
  dev_url: https://github.com/pganssle/zoneinfo

extra:
  recipe-maintainers:
    - kevans
    - dhirschfeld
