{% set name = "Flask-BasicAuth" %}
{% set version = "0.2.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "df5ebd489dc0914c224419da059d991eb72988a01cdd4b956d52932ce7d501ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  
  run:
    - python
    - flask

test:
  imports:
    - flask_basicauth

about:
  home: https://github.com/jpvanhal/flask-basicauth
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'HTTP basic access authentication for Flask.'
  doc_url: https://flask-basicauth.readthedocs.io/en/latest/
  dev_url: https://github.com/jpvanhal/flask-basicauth

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
