{% set name = "result" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/result-{{ version }}.tar.gz
  sha256: cc4147c824221e8326d143a55065ec17b6337a9c0dda7700f7f947ca33ac63fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - result
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rustedpy/result
  summary: A Rust-like result type for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
