{% set name = "starkbank-ecdsa" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f7b434b4a1e0ba082fb1804b908b79523973fd17b1fde377078857f7cee299d1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - ellipticcurve
    - ellipticcurve.utils
  requires:
    - pip
  commands:
    - pip check



about:
  home: https://github.com/starkbank/ecdsa-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A lightweight and fast pure python ECDSA library
  dev_url: https://github.com/starkbank/ecdsa-python
  doc_url: https://github.com/starkbank/ecdsa-python/blob/master/README.md

extra:
  recipe-maintainers:
    - cjmartian
