{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgbuild
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgbuild_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgbuild/pkgbuild_{{ version }}.tar.gz
  sha256: 357f3c40c99650eaa8a715991ff1355a553acb165f217ed204712f698ba55ed6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-callr >=3.2.0
    - r-cli
    - r-crayon
    - r-desc
    - r-prettyunits
    - r-rprojroot
    - r-withr >=2.1.2
  run:
    - r-base
    - r-r6
    - r-callr >=3.2.0
    - r-cli
    - r-crayon
    - r-desc
    - r-prettyunits
    - r-rprojroot
    - r-withr >=2.1.2

test:
  commands:
    - $R -e "library('pkgbuild')"           # [not win]
    - "\"%R%\" -e \"library('pkgbuild')\""  # [win]

about:
  home: https://github.com/r-lib/pkgbuild
  license: GPL-3.0-only
  summary: Provides functions used to build R packages. Locates compilers needed to build R packages on various platforms and ensures the PATH is configured appropriately so R can use them.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pkgbuild
# Title: Find Tools Needed to Build R Packages
# Version: 1.0.5
# Authors@R: c( person("Hadley", "Wickham", role = "aut"), person("Jim", "Hester", , "jim.hester@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# Description: Provides functions used to build R packages. Locates compilers needed to build R packages on various platforms and ensures the PATH is configured appropriately so R can use them.
# Imports: callr (>= 3.2.0), cli, crayon, desc, prettyunits, R6, rprojroot, withr (>= 2.1.2)
# Suggests: Rcpp, testthat, covr
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# URL: https://github.com/r-lib/pkgbuild
# BugReports: https://github.com/r-lib/pkgbuild/issues
# Depends: R (>= 3.1)
# NeedsCompilation: no
# Packaged: 2019-08-26 14:21:07 UTC; Administrator
# Author: Hadley Wickham [aut], Jim Hester [aut, cre], RStudio [cph]
# Maintainer: Jim Hester <jim.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-08-26 15:30:02 UTC
