{% set name = "Flask-Principal" %}
{% set version = "0.4.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f5d6134b5caebfdbb86f32d56d18ee44b080876a27269560a96ea35f75c99453" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - pip
    - python >=2.7

  run:
    - python >=2.7
    - flask
    - blinker

test:
  imports:
    - flask_principal

about:
  home: http://packages.python.org/Flask-Principal/
  license: MIT
  # in package but need new sdist on PyPi - see https://github.com/mattupstate/flask-principal/pull/16
  license_file: LICENSE 
  license_family: MIT
  summary: 'Identity management for flask'
  doc_url: https://pythonhosted.org/Flask-Principal/
  dev_url: https://github.com/mattupstate/flask-principal

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
