{% set version = '1.10' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-markdown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/markdown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/markdown/markdown_{{ version }}.tar.gz
  sha256: 211347b17065b8796a6899e047891220e23872f655bb6baa3b1b2a0f69d34be2

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown (>= 2.18), yaml, RCurl
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-commonmark >=1.9.0
    - r-xfun >=0.38

  run:
    - r-base
    - r-commonmark >=1.9.0
    - r-xfun >=0.38

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('markdown')"           # [not win]
    - "\"%R%\" -e \"library('markdown')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/markdown
  license: MIT
  summary: Render Markdown to full and lightweight HTML/LaTeX documents with the 'commonmark'
    package. It also supports features that are missing in 'commonmark', such as raw
    HTML/LaTeX blocks, LaTeX math, superscripts, subscripts, footnotes, element attributes,
    appendices, and fenced 'Divs'. With additional JavaScript and CSS, it can also create
    HTML slides and articles.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: markdown
# Type: Package
# Title: Render Markdown with 'commonmark'
# Version: 1.10
# Authors@R: c( person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("JJ", "Allaire", role = "aut"), person("Jeffrey", "Horner", role = "aut"), person("Henrik", "Bengtsson", role = "ctb"), person("Jim", "Hester", role = "ctb"), person("Yixuan", "Qiu", role = "ctb"), person("Kohske", "Takahashi", role = "ctb"), person("Adam", "November", role = "ctb"), person("Nacho", "Caballero", role = "ctb"), person("Jeroen", "Ooms", role = "ctb"), person("Thomas", "Leeper", role = "ctb"), person("Joe", "Cheng", role = "ctb"), person("Andrzej", "Oles", role = "ctb"), person(given = "Posit Software, PBC", role = c("cph", "fnd")) )
# Description: Render Markdown to full and lightweight HTML/LaTeX documents with the 'commonmark' package. It also supports features that are missing in 'commonmark', such as raw HTML/LaTeX blocks, LaTeX math, superscripts, subscripts, footnotes, element attributes, appendices, and fenced 'Divs'. With additional JavaScript and CSS, it can also create HTML slides and articles.
# Depends: R (>= 2.11.1)
# Imports: utils, commonmark (>= 1.9.0), xfun (>= 0.38)
# Suggests: knitr, rmarkdown (>= 2.18), yaml, RCurl
# License: MIT + file LICENSE
# URL: https://github.com/rstudio/markdown
# BugReports: https://github.com/rstudio/markdown/issues
# VignetteBuilder: knitr
# RoxygenNote: 7.2.3
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2023-10-10 03:49:02 UTC; yihui
# Author: Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>), JJ Allaire [aut], Jeffrey Horner [aut], Henrik Bengtsson [ctb], Jim Hester [ctb], Yixuan Qiu [ctb], Kohske Takahashi [ctb], Adam November [ctb], Nacho Caballero [ctb], Jeroen Ooms [ctb], Thomas Leeper [ctb], Joe Cheng [ctb], Andrzej Oles [ctb], Posit Software, PBC [cph, fnd]
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2023-10-10 05:20:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
