{% set name = "python-decouple" %}
{% set version = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba6e2657d4f376ecc46f77a3a615e058d93ba5e465c01bbe57289bfb7cce680f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  imports:
    - decouple
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HBNetwork/python-decouple
  doc_url: https://github.com/HBNetwork/python-decouple/blob/master/README.rst
  dev_url: https://github.com/HBNetwork/python-decouple
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Strict separation of config from code.
  description: |
    Decouple helps you to organize your settings so that you can change 
    parameters without having to redeploy your app.

extra:
  recipe-maintainers:
    - xmnlab
    - thewchan
