{% set name = "txaio" %}
{% set version = "23.1.1" %}
{% set sha256 = "f9a9216e976e5e3246dfd112ad7ad55ca915606b60b84a757ac769bd404ff704" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - txaio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/crossbario/txaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compatibility API between asyncio/Twisted/Trollius
  dev_url: https://github.com/crossbario/txaio
  doc_url: http://txaio.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
