{% set name = "datrie" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 525b08f638d5cf6115df6ccd818e5a01298cd230b2dac91c8ff2e6499d18765d

build:
  number: 0
  script: 
    - cython src/datrie.pyx
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed  -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - pytest-runner
    - setuptools
  run:
    - python

test:
  imports:
    - datrie

about:
  home: https://github.com/kmike/datrie/
  license: LGPLv2
  license_family: LGPL
  license_file: COPYING
  summary: Super-fast, efficiently stored Trie for Python, uses libdatrie
  doc_url: https://pypi.python.org/pypi/datrie
  dev_url: https://github.com/kmike/datrie/

extra:
  recipe-maintainers:
    - melund
    - tacaswell
