{% set name = "aom" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://storage.googleapis.com/aom-releases/libaom-{{ version }}.tar.gz
  sha256: a4a6c0fab685da743b796662a928fcdf7ae60594edc306efb73e78a17ea6cde6
  patches:
    - do_not_link_to_libm_windows.patch

build:
  number: 0
  run_exports:
    # Just a guess...
    - {{ pin_subpackage('aom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - perl
    - nasm      # [x86_64]
    # we need binutils for the `as` executable
    - binutils  # [aarch64]
    - make      # [unix]
    - patch     # [not win]
    - m2-patch  # [win]
test:
  commands:
    - aomenc --help  # [build_platform == target_platform]
    - aomdec --help  # [build_platform == target_platform]
    - test -f ${PREFIX}/include/aom/aom.h            # [unix]
    - test -f ${PREFIX}/lib/libaom${SHLIB_EXT}       # [unix]
    - test ! -f ${PREFIX}/lib/libaom.a               # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/aom.pc         # [unix]
    - if not exist %LIBRARY_INC%\\aom\\aom.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\aom.dll exit 1     # [win]

about:
  home: https://aomedia.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Alliance for Open Media video codec
  description: |
    AOMedia Video 1 (AV1), is an open, royalty-free video coding format designed for
    video transmissions over the Internet.
  dev_url: https://aomedia.googlesource.com/aom/
  doc_url: https://aomedia.googlesource.com/aom/
extra:
  recipe-maintainers:
    - matthiasdiener
