{% set name = "asgi-lifespan" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asgi-lifespan-{{ version }}.tar.gz
  sha256: 9a33e7da2073c4764bc79bd6136501d6c42f60e3d2168ba71235e84122eadb7f

build:
  number: 5
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - async-exit-stack
    - python >=3.7
    - sniffio

test:
  imports:
    - asgi_lifespan
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/florimondmanca/asgi-lifespan
  summary: Programmatic startup/shutdown of ASGI apps.
  license: MIT
  license_file: LICENSE
  
extra:
  recipe-maintainers:
    - williamjamir
