{% set version = "1.12" %}

package:
  name: patool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/patool/patool-{{ version }}.tar.gz
  sha256: e3180cf8bfe13bedbcf6f5628452fca0c2c84a3b5ae8c2d3f55720ea04cb1097

build:
  number: 1006
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - patoolib
    - patoolib.programs
  commands:
    - patool --help

about:
  home: http://wummel.github.io/patool/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'portable archive file manager'
  dev_url: https://github.com/wummel/patool

extra:
  recipe-maintainers:
    - notestaff
    - ocefpaf
