{% set version = "0.6.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpubr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggpubr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpubr/ggpubr_{{ version }}.tar.gz
  sha256: 2e6ec5d8151991d17ef8832259cf545fa0d1a50b326ba8c1c4657700171df774

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cowplot
    - r-dplyr >=0.7.1
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-glue
    - r-gridextra
    - r-magrittr
    - r-polynom
    - r-purrr
    - r-rlang
    - r-scales
    - r-tidyr
    - r-rstatix
  run:
    - r-base
    - r-cowplot
    - r-dplyr >=0.7.1
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-glue
    - r-gridextra
    - r-magrittr
    - r-polynom
    - r-purrr
    - r-rlang
    - r-scales
    - r-tidyr
    - r-rstatix

test:
  commands:
    - $R -e "library('ggpubr')"           # [not win]
    - "\"%R%\" -e \"library('ggpubr')\""  # [win]

about:
  home: https://rpkgs.datanovia.com/ggpubr/
  license: GPL-2.0-only
  summary: The 'ggplot2' package is excellent and flexible for elegant data visualization in R. However the default generated plots requires some formatting before we can send them for publication. Furthermore, to customize a 'ggplot', the syntax is opaque and this raises the level of difficulty for researchers with no advanced
    R programming skills. 'ggpubr' provides some easy-to-use functions for creating and customizing 'ggplot2'- based publication ready plots.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggpubr
# Type: Package
# Title: 'ggplot2' Based Publication Ready Plots
# Version: 0.2.3
# Date: 2019-09-03
# Authors@R: c( person("Alboukadel", "Kassambara", role = c("aut", "cre"), email = "alboukadel.kassambara@gmail.com"))
# Description: The 'ggplot2' package is excellent and flexible for elegant data visualization in R. However the default generated plots requires some formatting before we can send them for publication. Furthermore, to customize a 'ggplot', the syntax is opaque and this raises the level of difficulty for researchers with no advanced R programming skills. 'ggpubr' provides some easy-to-use functions for creating and customizing 'ggplot2'- based publication ready plots.
# License: GPL-2
# LazyData: TRUE
# Encoding: UTF-8
# Depends: R (>= 3.1.0), ggplot2, magrittr
# Imports: ggrepel, grid, ggsci, stats, utils, tidyr, purrr, dplyr (>= 0.7.1), cowplot, ggsignif, scales, gridExtra, glue, polynom, rlang
# Suggests: grDevices, knitr, RColorBrewer, gtable
# URL: https://rpkgs.datanovia.com/ggpubr/
# BugReports: https://github.com/kassambara/ggpubr/issues
# RoxygenNote: 6.1.1
# Collate: 'utilities_color.R' 'utilities_base.R' 'desc_statby.R' 'utilities.R' 'add_summary.R' 'annotate_figure.R' 'as_ggplot.R' 'axis_scale.R' 'background_image.R' 'bgcolor.R' 'border.R' 'compare_means.R' 'diff_express.R' 'facet.R' 'font.R' 'gene_citation.R' 'geom_bracket.R' 'geom_exec.R' 'get_legend.R' 'get_palette.R' 'ggadd.R' 'ggarrange.R' 'ggballoonplot.R' 'ggpar.R' 'ggbarplot.R' 'ggboxplot.R' 'ggdensity.R' 'ggpie.R' 'ggdonutchart.R' 'stat_conf_ellipse.R' 'stat_chull.R' 'ggdotchart.R' 'ggdotplot.R' 'ggecdf.R' 'ggerrorplot.R' 'ggexport.R' 'gghistogram.R' 'ggline.R' 'ggmaplot.R' 'ggpaired.R' 'ggparagraph.R' 'ggpubr_args.R' 'ggqqplot.R' 'utilities_label.R' 'stat_cor.R' 'stat_stars.R' 'ggscatter.R' 'ggscatterhist.R' 'ggstripchart.R' 'ggtext.R' 'ggtexttable.R' 'ggviolin.R' 'gradient_color.R' 'grids.R' 'reexports.R' 'rotate.R' 'rotate_axis_text.R' 'rremove.R' 'set_palette.R' 'show_line_types.R' 'show_point_shapes.R' 'stat_central_tendency.R' 'stat_compare_means.R' 'stat_mean.R' 'stat_overlay_normal_density.R' 'stat_pvalue_manual.R' 'stat_regline_equation.R' 'text_grob.R' 'theme_pubr.R' 'theme_transparent.R'
# NeedsCompilation: no
# Packaged: 2019-09-03 21:16:16 UTC; kassambara
# Author: Alboukadel Kassambara [aut, cre]
# Maintainer: Alboukadel Kassambara <alboukadel.kassambara@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-03 22:00:02 UTC
