{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cowplot
  version: {{ version|replace("-", "_") }}

source:
  fn: cowplot_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/cowplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cowplot/cowplot_{{ version }}.tar.gz
  sha256: c7dce625b456dffc59ba100c816e16226048d12fdd29a7335dc1f6f6e12eed48

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >2.2.1
    - r-gtable
    - r-rlang
    - r-scales
  run:
    - r-base
    - r-ggplot2 >2.2.1
    - r-gtable
    - r-rlang
    - r-scales

test:
  commands:
    - $R -e "library('cowplot')"           # [not win]
    - "\"%R%\" -e \"library('cowplot')\""  # [win]

about:
  home: https://github.com/wilkelab/cowplot
  license: GPL-2.0-only
  summary: Some helpful extensions and modifications to the 'ggplot2' package. In particular, this package makes it easy to combine multiple 'ggplot2' plots into one and label them with letters, e.g. A, B, C, etc., as is often required for scientific publications. The package also provides a streamlined and clean theme that
    is used in the Wilke lab, hence the package name, which stands for Claus O. Wilke's plot package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - druvus
